name: Criar pasta via SSH

on:
  push:
    branches:
      - main

jobs:
  criar-pasta:
    runs-on: ubuntu-latest
    steps:
      - name: Conectar ao servidor remoto via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SFTP_SERVER }}
          username: marcelo.vasconcelos@vizcaya.com.br
          password: M09o092021*os
          key: ${{ secrets.SSH_PRIVATE_KEY2 }}
          port: 5051
          script: |
            mkdir teste2
