name: VPN
on:
    push:
        branches: [ main ]
    workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run a Multi-Line Script
      run: |
        echo 1 - Extrair
            ping 192.168.169.23
        echo 2 - Instalar Lib
            ls
        echo 3 - Instalar VPN
            chmod +x ./linux_phat_client/install_linux_phat_client.sh
            sudo ./linux_phat_client/install_linux_phat_client.sh
      shell: bash
