name: VPN
on:
    push:
        branches: [ main ]
    workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Instalação da VPN
      run: |
            sudo mkdir /opt/sslvpn-plus
            sudo mkdir /opt/sslvpn-plus/naclient
            sudo cp -rf linux_phat_client/linux_phat_client/* /opt/sslvpn-plus/naclient/
            sudo chmod -R 777 /opt/sslvpn-plus/naclient/
            sudo chmod -R 777 ./linux_phat_client/install_linux_phat_client.sh
            sudo ./linux_phat_client/install_linux_phat_client.sh
    - name: Conectar VPN
      run:  |
             sudo naclient login
             echo "y"
             -profile DBB
    - name: Teste de conexão
      run:
        ping -c 4 192.168.169.21
      shell: bash
