name: VPN
on:
    push:
        branches: [ main ]
    workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Instalação da VPN
      run: |
        echo 1 - criar pasta
            sudo mkdir /opt/sslvpn-plus
        echo 2 - criar pasta
            sudo mkdir /opt/sslvpn-plus/naclient
        echo 3 - copiar pasta
            sudo cp -rf linux_phat_client/linux_phat_client/* /opt/sslvpn-plus/naclient/
        echo 5 - Instalar VPN
            sudo chmod -R 777 /opt/sslvpn-plus/naclient/
            sudo chmod -R 777 ./linux_phat_client/install_linux_phat_client.sh
            sudo ./linux_phat_client/install_linux_phat_client.sh
    - name: Conectar VPN
      run:
            echo y | sudo naclient login -profile DBB -user VPN_TI_DBB -password Ti@DBB2020
            echo end
    - name: teste de conexão
      run:
        ping -c 4 8.8.8.8
      shell: bash
