name: Upload to SFTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Upload via SFTP
        run: |
          apt-get install ftp-upload
          npx ftp-upload --remote-root / --local-root ./aprovação.jpg --user ${{ secrets.SFTP_USERNAME }} --password ${{ secrets.SFTP_PASSWORD }} --host ${{ secrets.SFTP_SERVER }} --port ${{ secrets.SFTP_PORT || '22' }} --protocol sftp
